env:
  es2022: true
  node: true
  jest: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: off
  import/extensions: off
  func-names:
    - error
    - never
  no-underscore-dangle:
    - error
    - allow:
      - __filename
      - __dirname
